//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5485.
// 
#pragma warning disable 1591

namespace TestReforzamiento.reforzamiento {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AsistenciasSoap", Namespace="http://localhost:23968/")]
    public partial class Asistencias : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DecryptQROperationCompleted;
        
        private System.Threading.SendOrPostCallback ConfirmaAsistenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback PJsonResultOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Asistencias() {
            this.Url = global::TestReforzamiento.Properties.Settings.Default.TestReforzamiento_reforzamiento_Asistencias;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DecryptQRCompletedEventHandler DecryptQRCompleted;
        
        /// <remarks/>
        public event ConfirmaAsistenciaCompletedEventHandler ConfirmaAsistenciaCompleted;
        
        /// <remarks/>
        public event PJsonResultCompletedEventHandler PJsonResultCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:23968/DecryptQR", RequestNamespace="http://localhost:23968/", ResponseNamespace="http://localhost:23968/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DecryptQR(string codigo) {
            object[] results = this.Invoke("DecryptQR", new object[] {
                        codigo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DecryptQRAsync(string codigo) {
            this.DecryptQRAsync(codigo, null);
        }
        
        /// <remarks/>
        public void DecryptQRAsync(string codigo, object userState) {
            if ((this.DecryptQROperationCompleted == null)) {
                this.DecryptQROperationCompleted = new System.Threading.SendOrPostCallback(this.OnDecryptQROperationCompleted);
            }
            this.InvokeAsync("DecryptQR", new object[] {
                        codigo}, this.DecryptQROperationCompleted, userState);
        }
        
        private void OnDecryptQROperationCompleted(object arg) {
            if ((this.DecryptQRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DecryptQRCompleted(this, new DecryptQRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:23968/ConfirmaAsistencia", RequestNamespace="http://localhost:23968/", ResponseNamespace="http://localhost:23968/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConfirmaAsistencia(int asistencia) {
            object[] results = this.Invoke("ConfirmaAsistencia", new object[] {
                        asistencia});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConfirmaAsistenciaAsync(int asistencia) {
            this.ConfirmaAsistenciaAsync(asistencia, null);
        }
        
        /// <remarks/>
        public void ConfirmaAsistenciaAsync(int asistencia, object userState) {
            if ((this.ConfirmaAsistenciaOperationCompleted == null)) {
                this.ConfirmaAsistenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConfirmaAsistenciaOperationCompleted);
            }
            this.InvokeAsync("ConfirmaAsistencia", new object[] {
                        asistencia}, this.ConfirmaAsistenciaOperationCompleted, userState);
        }
        
        private void OnConfirmaAsistenciaOperationCompleted(object arg) {
            if ((this.ConfirmaAsistenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConfirmaAsistenciaCompleted(this, new ConfirmaAsistenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:23968/PJsonResult", RequestNamespace="http://localhost:23968/", ResponseNamespace="http://localhost:23968/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Resultado PJsonResult(int asistencia) {
            object[] results = this.Invoke("PJsonResult", new object[] {
                        asistencia});
            return ((Resultado)(results[0]));
        }
        
        /// <remarks/>
        public void PJsonResultAsync(int asistencia) {
            this.PJsonResultAsync(asistencia, null);
        }
        
        /// <remarks/>
        public void PJsonResultAsync(int asistencia, object userState) {
            if ((this.PJsonResultOperationCompleted == null)) {
                this.PJsonResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPJsonResultOperationCompleted);
            }
            this.InvokeAsync("PJsonResult", new object[] {
                        asistencia}, this.PJsonResultOperationCompleted, userState);
        }
        
        private void OnPJsonResultOperationCompleted(object arg) {
            if ((this.PJsonResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PJsonResultCompleted(this, new PJsonResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:23968/")]
    public partial class Resultado {
        
        private string alumnoField;
        
        private string eventoField;
        
        private string expositorField;
        
        private string lugarField;
        
        private string fechaField;
        
        private string horaField;
        
        private string ingresoField;
        
        private string salidaField;
        
        private string messageField;
        
        private string fotoField;
        
        private string asistenciaField;
        
        /// <remarks/>
        public string alumno {
            get {
                return this.alumnoField;
            }
            set {
                this.alumnoField = value;
            }
        }
        
        /// <remarks/>
        public string evento {
            get {
                return this.eventoField;
            }
            set {
                this.eventoField = value;
            }
        }
        
        /// <remarks/>
        public string expositor {
            get {
                return this.expositorField;
            }
            set {
                this.expositorField = value;
            }
        }
        
        /// <remarks/>
        public string lugar {
            get {
                return this.lugarField;
            }
            set {
                this.lugarField = value;
            }
        }
        
        /// <remarks/>
        public string fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        public string hora {
            get {
                return this.horaField;
            }
            set {
                this.horaField = value;
            }
        }
        
        /// <remarks/>
        public string ingreso {
            get {
                return this.ingresoField;
            }
            set {
                this.ingresoField = value;
            }
        }
        
        /// <remarks/>
        public string salida {
            get {
                return this.salidaField;
            }
            set {
                this.salidaField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
            }
        }
        
        /// <remarks/>
        public string asistencia {
            get {
                return this.asistenciaField;
            }
            set {
                this.asistenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void DecryptQRCompletedEventHandler(object sender, DecryptQRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DecryptQRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DecryptQRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void ConfirmaAsistenciaCompletedEventHandler(object sender, ConfirmaAsistenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfirmaAsistenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConfirmaAsistenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    public delegate void PJsonResultCompletedEventHandler(object sender, PJsonResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PJsonResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PJsonResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resultado)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591